[package]
name = "program"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
no-entrypoint = []

[dependencies.pinocchio]
version = "0.8.4"
[dependencies.pinocchio-pubkey]
version = "0.2.4 "

[dev-dependencies.litesvm_client]
git = "https://github.com/bonedaddy/litesvm-client"
rev = "3030a4b50db5c6edae67cc2ed8fda4204418fbeb"
[dev-dependencies.solana-sdk]
version = "2"
[dev-dependencies.litesvm]
version = "0.6.1"
